---
- name: Ensure that system dependencies are installed (RPM-based)
  package:
    name="{{ interconnect_dependencies }}"
    state=present

- name: Ensure that java is installed
  include_role:
    name: ansiblebit.oracle-java
    tasks_from: main.yml

- name: Install nodejs and npm package
  include_role:
    name: nodejs
    tasks_from: main.yml
